# Generated by Django 4.2.8 on 2026-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_inventoryitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/'),
        ),
    ]
